name: instagram_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  firebase_auth_web:
  firebase_messaging: ^14.1.1
  firebase_storage: ^11.0.6
  flutter_svg: ^2.0.5
  flutter_staggered_grid_view: ^0.6.2
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  http: ^0.13.4
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  uuid: ^3.0.5
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core_platform_interface: 4.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
