name: instagram_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.12
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.1
  get: ^4.6.1
  google_fonts: ^3.0.1
  http: ^0.13.4
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  uuid: ^3.0.5
  flutter_staggered_grid_view: ^0.6.1
  device_preview: ^1.1.0
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
