// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6IpwJc1XKEjkPYYUctkz9RbkhbSk4y-E',
    appId: '1:874976605457:web:42f23daf5006e259b2c8b0',
    messagingSenderId: '874976605457',
    projectId: 'instagram-clone-fcc-b99b8',
    authDomain: 'instagram-clone-fcc-b99b8.firebaseapp.com',
    storageBucket: 'instagram-clone-fcc-b99b8.appspot.com',
    measurementId: 'G-3S4X39EJG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHuS9HmONX5AZCKZAdFkuULhw3hxwSr_Q',
    appId: '1:874976605457:android:4423f323babde19bb2c8b0',
    messagingSenderId: '874976605457',
    projectId: 'instagram-clone-fcc-b99b8',
    storageBucket: 'instagram-clone-fcc-b99b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33NAwH6Np-rzZS9dzyG-zTu441Jt1Xuk',
    appId: '1:874976605457:ios:298b955239911ec2b2c8b0',
    messagingSenderId: '874976605457',
    projectId: 'instagram-clone-fcc-b99b8',
    storageBucket: 'instagram-clone-fcc-b99b8.appspot.com',
    iosClientId: '874976605457-avs3eq72u7krptiq21n6doigl8upbc4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
